### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by DiamondBullet54** [Gant696t04/PasteGameChapter1#1]
Feelings is spelled wrong on line 17
![image](https://user-images.githubusercontent.com/93168049/193161764-d0c25e73-25ef-4af8-b358-24dcec581e73.png)

**Comment by Gant696t04** [comment]
No... I don't think I did.

**Comment by DiamondBullet54** [comment]
[Meet the [Demoman](https://wiki.teamfortress.com/wiki/Demoman) Title Card]

[Opening fanfare of [Drunken Pipe Bomb](https://wiki.teamfortress.com/wiki/Drunken_Pipe_Bomb) plays as the Demoman narrowly escapes a massive explosion while jumping from a drop-down corridor in [Gravel Pit](https://wiki.teamfortress.com/wiki/Gravel_Pit).]

[Freeze frame]

Demoman: "What makes me a good Demoman?"

[Cut to Demoman, sitting in a room full of explosives.]

Demoman: "If I were a bad Demoman, I wouldn't be sittin' here, discussin' it with you now would I?"

["Drunken Pipe Bomb" resumes playing]

[Demoman charges into battle along with Team [RED](https://wiki.teamfortress.com/wiki/RED) while dodging a cascade of [rockets](https://wiki.teamfortress.com/wiki/Rocket_Launcher).]

Demoman: "Let's do it!"

Demoman: "Not one of ya's gonna' survive this."

[Cut back to the Demoman's room, music pauses.]

Demoman: "One crossed wire, one wayward pinch of potassium chlorate, one errant twitch... and kablooie!"

[Cut back to battle, music resumes.]

[The Demoman bounces a [grenade](https://wiki.teamfortress.com/wiki/Grenade_Launcher) off a wall and [gibs](https://wiki.teamfortress.com/wiki/Gibs) a pursuing [Pyro](https://wiki.teamfortress.com/wiki/Pyro).]

[Cut to scene of the Demoman chugging from his [Bottle](https://wiki.teamfortress.com/wiki/Bottle) of scrumpy.]

[A level 2 [Sentry Gun](https://wiki.teamfortress.com/wiki/Sentry_Gun) upgrades to level 3.]

[Cut to scene of the Demoman continuing to chug from his Bottle of scrumpy.]

[Sentry Gun fires rockets at the Demoman.]

[Cut to a close up of the Demoman's face, still chugging from his Bottle of scrumpy.]

[The Demoman dodges the rockets as a nearby [Scout](https://wiki.teamfortress.com/wiki/Scout) is gunned down by the Sentry. The Demoman then fires two grenades, destroying the Sentry Gun.]

[Cut back to Demoman's room, music stops.]

[The Demoman slams the now empty Bottle down on the table, breathing heavily.]

[Camera blurs.]

Demoman: "I got a manky eye. I'm a black, Scottish cyclops."

[The Demoman knocks a grenade off the table, arming it in the process (it begins to blink).]

Demoman: They've got more f-[long censored]-s than they've got the likes of me."

[The Demoman starts to drink from the empty Bottle, then notices the camera and becomes lucid again.]

Demoman: "So...."

[The ending segment of "Drunken Pipe Bomb" starts to play.]

Demoman: "...T'all you fine dandies so proud, so cocksure."

[The Demoman runs out to the final capture point in Gravelpit and is shocked to see a group of [BLU](https://wiki.teamfortress.com/wiki/BLU) team members charging towards him with smug expressions on their faces. A devious look comes over the Demoman's face and he runs with BLU in hot pursuit.]

Demoman: "Prancin' aboot with your heads full of eyeballs! Come and get me I say! [The Demoman passes a door frame and covers it in [sticky bombs](https://wiki.teamfortress.com/wiki/Stickybomb_Launcher)] I'll be waiting on ya with a whiff of the 'ol brimstone. I'm a grim bloody fable... with an unhappy bloody end!"

[The Heavy notices the sticky bombs around the door frame, and his expression changes from smugness to one of shock. The Demoman throws a mock salute and activates the sticky bombs, [gibbing](https://wiki.teamfortress.com/wiki/Gibs) all his pursuers.]

[The Demoman walks up to (presumably) a decapitated head, laughing merrily as body parts and blood rain down around him.]

Demoman: "Oh, they're going to have to glue you back together... in hell!"

[Team Fortress 2 ending flourish music plays, accompanied by bagpipes.]
